name: Docker Image CI

on:
  workflow_call:
    inputs:
      target:
        required: false
        type: string
        default: "."
        
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build app/backend/ --tag weather-api:$(date +%s)
